### ISSUE TITLE
Some Songs in the album not downloading

### ISSUE THREAD

**Issue by Jayanthbm** [naqushab/saavn-downloader-extension#16]
I am trying to download songs from this album 
https://www.jiosaavn.com/album/preethsod-thappa.../kMH2Vsh64h0_

the first song in the album is downloaded but the 4th and 7th songs are not downloading
the link text download next to sog changed to downloading

Error log and Screen attached below
<img width="636" alt="screenshot 2019-01-15 at 8 00 15 am" src="https://user-images.githubusercontent.com/14847969/51154950-df7cb400-189b-11e9-91dd-3162b396d064.png">
<img width="551" alt="screenshot 2019-01-15 at 8 01 43 am" src="https://user-images.githubusercontent.com/14847969/51154955-e3a8d180-189b-11e9-873f-2d681401589c.png">

**Comment by mujunk** [comment]
I have the same issue. Only 27 songs from a 55 song playlist downloaded.
https://www.jiosaavn.com/featured/90s-king---kumar-sanu/QeBmhG7Y1uE_

**Comment by naqushab** [comment]
The reason that some songs are of few KBs in size is because they are not available in selected quality (320kbps for example). Try changing the Download quality from top right dropdown and see if problem persists. There is no way to see if a song is available in a mentioned quality.
Playlist and Albums can have such songs will will lead to having such files in them too. Try selecting the next best quality there too.
