### ISSUE TITLE
Songs of Playlist downloaded in 100-200 kb size

### ISSUE THREAD

**Issue by kshaik7** [naqushab/saavn-downloader-extension#18]
When i download songs off a playlist they only download a file with nothing but the name of the song.

**Comment by kshaik7** [comment]
Also when downloading playlists not all songs are downloaded. For ex: out of a playlist of 10-15 songs, 4 will be successfully downloaded.

**Comment by naqushab** [comment]
The reason that some songs are of few KBs in size is because they are not available in selected quality (320kbps for example). Try changing the Download quality from top right dropdown and see if problem persists. There is no way to see if a song is available in a mentioned quality.
Playlist and Albums can have such songs will will lead to having such files in them too. Try selecting the next best quality there too.
