### ISSUE TITLE
this is not working for download song from jiosaavan new web page 

### ISSUE THREAD

**Issue by Sanj2020** [naqushab/saavn-downloader-extension#33]
Sir I love this extension but few days the Jiosaavan.com update his web page so new page I can download any song with this extension so I request to you please fix this

**Comment by HritwikSinghal** [comment]
@naqushab saavn changed the url of song after decrpytion, now its 'aac.saavncdn.com/935/e234433555a6c343c2c8b6576db66c32_96.mp4' 
which redirects to any one of jio cdn ( like 'http://schnncdnems02.cdnsrv.jio.com/h.saavncdn.com/935/e234433555a6c343c2c8b6576db66c32_96.mp4') and this url has new song.

so after redirecting, just replace the '_96.mp4' part in last with '_320.mp3' and check if 200 status is returned, if not replace the '_96.mp4' part in last with '_160.mp3' and again check. if not, replace the '_96.mp4' part in last with '.mp3' for 128kbps.

i dont know javascript thats why i couldn't do it. Please look into it

**Comment by naqushab** [comment]
Thank you. I'll look into it and get back to you. Thanks for the
investigation, it will help.

**Comment by onlynir** [comment]
naqushab Sir, please develop one tool for Gaana also.  I have more than 50 albums link which is not available at Savaan.  Therefore I am not able to download those albums. I am eagerly requesting to You.

**Comment by naqushab** [comment]
> naqushab Sir, please develop one tool for Gaana also. I have more than 50 albums link which is not available at Savaan. Therefore I am not able to download those albums. I am eagerly requesting to You.

Its a feature request. I would try to move to a unified approach but not in a foreseeable future.

**Comment by naqushab** [comment]
@HritwikSinghal how did you came across this new URL? I can search for the decrypting logic but it would be easier if you just told me and I reuse that. :)

**Comment by HritwikSinghal** [comment]
> @HritwikSinghal how did you came across this new URL? I can search for the decrypting logic but it would be easier if you just told me and I reuse that. :)

Saavn changed their whole interface again, so now i get encrypted media url from their api. Then i decrypt it using the already known scheme which is used till now, Then the url looks like this "http://aac.saavncdn.com/430/5c5ea5cc00e3bff45616013226f376fe_96.mp4" so replace '_96' with '_320' and open it in browser tab. so That would Be the download Url now.

Now, if you replace 'aac.saavncdn.com' with 'h.saavncdn.com', and open the url ( which is now "http://h.saavncdn.com/430/5c5ea5cc00e3bff45616013226f376fe_320.mp4"), it will automatically redirect to one of cdn server. 
But AFAIK there is no need for this method. Just use the "aac.saavncdn.com/" Url and it serves the song. For API you can see 'https://github.com/monuyadav016/Saavn-Downloader'

**Comment by naqushab** [comment]
good stuff @HritwikSinghal ! I'll give it a read. meanwhile I have added the download option back using an unoffical Jiosaavn api.
