### ISSUE TITLE
[BUG] Download progress bar is missing 

### ISSUE THREAD

**Issue by ADVALAKI** [naqushab/saavn-downloader-extension#43]
**Describe the bug**

**To Reproduce**
1. Go to URL '...' : Open Any song
2. Click on '....' : Click on Download button its only show clock icon. ( download progress-bar is missing)
3. See error : BasicallySongs downloaded successfully in background. but progress bar is missing. 

**Expected behavior**
Should display download progress bar.
 
**Screenshots**

**Additional context**

**Comment by naqushab** [comment]
Hi @ADVALAKI ,
Actually after the UI overhaul i decided not to put more work on download bar on bottom as it itself is more work. And if you've seen the jiosaavn pro, the download progress is consistent with what I have provided.
I'd happy to accept any PR to add it in case someone wants to add, but for now this will be an enhancement and more of a nice to have feature.

**Comment by ADVALAKI** [comment]
you mean to say in jiosavan pro progress bar is working fine.?

By the way you have done great work on this two days to make this extension functional again.

hats off for this. :+1:

**Comment by naqushab** [comment]
No. I meant there is no progress bar in JioSaavn pro as well (which has the official download option support). It also shows this downloading circle when clicked on Download icon. The progress bar changes take a lot of time and itself is quite buggy which is why I used Jiosaavn's own downloading icon and not that. Hopefully, once I am done with all functional changes I can re-look into that again.

Thank you for the kind words, and sorry I couldn't do it sooner. I got quite caught up in other stuff.

**Comment by cachecleanerjeet** [comment]
@ADVALAKI , Now it will update you by some notifications. Progress bar is not practical for https://github.com/naqushab/saavn-downloader-extension/commit/d42bf2b8435733562f22161616580b947a3cc136 as it have to fetch and convert the song into mp3. So it will update you with some notifications, if your download has been failed due to some reason, it will still notify you.

**Comment by naqushab** [comment]
Workaround provided. Closing the issue.
