### ISSUE TITLE
Full album downloads doesn’t work 

### ISSUE THREAD

**Issue by BobWs** [naqushab/saavn-downloader-extension#5]
Tried the extensions (Firefox and chrome) but full album download does not work properly. When you click on the download button next to the album title it seems that the download starts but after a while nothing happens there is no file or whatever. 

Also when downloading single songs not all of the songs are downloaded. With chrome empty mp3 files where downloaded. And with Firefox nothing happened.

**Comment by naqushab** [comment]
Can you please provide the link of the song and the albums you want to download? My guess is, the song isn't available in the quality mentioned by you, that's why it is giving nothing/empty file.

**Comment by BobWs** [comment]
This is the album I tested: 
https://www.saavn.com/s/album/hindi/Om-Shanti-Om-2007/EPJXYk,wkdA_?&utm_content=wap:search_results:top_result:select_album:click&utm_page=search_results&utm_button=top_result

**Comment by naqushab** [comment]
The reason that some songs are of few KBs in size is because they are not available in selected quality (320kbps for example). Try changing the Download quality from top right dropdown and see if problem persists. There is no way to see if a song is available in a mentioned quality.
Playlist and Albums can have such songs will will lead to having such files in them too. Try selecting the next best quality there too.
